---
- name: using ansible to send an http get
  hosts: localhost
  connection: local
  gather_facts: false

  tasks:
    - name: send http get to requestbin.com
      ansible.builtin.uri:
        url: "{{ urltolookup }}?name=student&policy=bronze&storage_type=flash"
        method: GET
        headers:
          Content-Type: application/json
          Storage-auth-token: abcdefg717
      register: results


    - name: display results
      ansible.builtin.debug:
        var: results

