---
- name: use redfish to gather cpu inventory and virtual media info
  hosts: Redfish
  connection: local
  gather_facts: false

  collections:
    - community.general

  tasks:

    - name: get cpu inventory
      community.general.redfish_info:
        category: Systems
        command: GetCpuInventory
        baseuri: "{{ baseuri }}"
        username: "{{ username }}"
        password: "{{ password }}"
      register: cpuInv

    - name: display cpu data
      ansible.builtin.debug:
        var: cpuInv


    - name: get virtual media info
      community.general.redfish_info:
        category: Manager
        command: GetVirtualMedia
        baseuri: "{{ baseuri }}"
        username: "{{ username }}"
        password: "{{ password }}"
      register: mediaInformation

    - name: show virtual media information
      ansible.builtin.debug:
        var: mediaInformation
